[package]
name = "meowsn"
version = "0.7.0"
edition = "2024"

[dependencies]
dark-light = "2.0.0"
iced = { version = "0.14.0-dev", features = ["sipper", "tokio", "image", "svg"] }
iced_aw = { version = "0.13.0-dev", default-features = false, features = ["context_menu"] }
tokio = { version = "1.47.0", default-features = false, features = ["time"] }
msnp11-sdk = "0.8.2"
keyring = { version = "3", features = ["apple-native", "windows-native", "sync-secret-service"] }
dirs = "6.0.0"
r2d2 = "0.8.10"
r2d2_sqlite = { version = "0.31.0", features = ["bundled"] }
toml = { version = "0.9.2", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
rfd = "0.15.4"
image = "0.25.6"
notify-rust = "4.11.7"
reqwest = { version = "0.12.23", features = ["json"] }
semver = "1.0.26"

[patch.crates-io]
iced = { git = "https://github.com/campos02/iced", rev = "0a34496c793fd87c235e764317351a0aacd4f6d1" }
iced_core = { git = "https://github.com/campos02/iced", rev = "0a34496c793fd87c235e764317351a0aacd4f6d1" }
iced_widget = { git = "https://github.com/campos02/iced", rev = "0a34496c793fd87c235e764317351a0aacd4f6d1" }
iced_aw = { git = "https://github.com/campos02/iced_aw", rev = "4ce2b07fab58a926567e485f0bdf7fb686cba6bf" }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
split-debuginfo = "packed"
strip = "symbols"
incremental = true

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1.22"
