[package]
name = "icedm"
version = "0.1.0"
edition = "2024"

[dependencies]
dark-light = "2.0.0"
iced = { version = "0.13.1", features = ["debug", "tokio", "image", "svg"] }
iced_aw = { version = "0.12.0", default-features = false, features = ["context_menu"] }
tokio = { version = "1.47.0", default-features = false, features = ["time"] }
msnp11-sdk = "0.6.4"
keyring = { version = "3", features = ["apple-native", "windows-native", "sync-secret-service"] }
dirs = "6.0.0"
r2d2 = "0.8.10"
r2d2_sqlite = { version = "0.31.0", features = ["bundled"] }
toml = { version = "0.9.2", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
rfd = "0.15.4"
image = "0.25.6"
notify-rust = "4.11.7"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
split-debuginfo = "packed"
strip = "symbols"
incremental = true

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1.22"