name: Build for macOS
on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-arm:
    strategy:
      matrix:
        BUILD_TARGET: [release]
        
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
      run: cargo build --profile ${{ matrix.BUILD_TARGET }}
      
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: icedm-arm
        path: target/${{ matrix.BUILD_TARGET }}/icedm

  build-x86:
    strategy:
      matrix:
        BUILD_TARGET: [release]
        
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
      run: cargo build --profile ${{ matrix.BUILD_TARGET }}
      
    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: icedm-x86
        path: target/${{ matrix.BUILD_TARGET }}/icedm
